spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  mustache:
    suffix: .mustache
    charset: UTF-8

jwt:
  access-expiration: 3600000      # 1시간 (밀리초)
  refresh-expiration: 1209600000  # 14일 (밀리초)

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  swagger-ui:
    path: /api-docs
